### PR TITLE
Add functions to return tbscert, stripping sct/poison

### PR DESCRIPTION
**Pull request by 0xxon**
x509_tbscert_strip_sct returns the tbscert without sct

x509_tbscert_strip_poison does the same with poison

### CODE REVIEW

**Comment by lexibrent** [comment]
Looks good to me. Will merge after my [upstream PR](https://github.com/crtsh/libx509pq/pull/1) has been resolved. Alternatively, you could submit a PR directly to the upstream COMODO repo.

**Comment by 0xxon** [comment]
Ah, you want your changes to be merged upstream. I don't think they will want to accept this (and I won't blame them) - this is too specific to our needs.

**Comment by lexibrent** [comment]
I was hoping they would merge just my changes to the build framework, but agree that your PR is probably too specific for their purposes.

**Comment by robstradling** [comment]
These functions seem useful, so I'd take a PR for this upstream.

**Pull request merged**
